# Generated by Django 3.0.6 on 2020-05-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='activatee',
            new_name='activate',
        ),
    ]
