# Generated by Django 3.0.6 on 2020-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images/<django.db.models.query_utils.DeferredAttribute object at 0x7f88bf3a40d0>'),
        ),
    ]
